spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_management
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

env: development

token:
  secret: ${SECRET_KEY}
